[tox]
min_version = 4.0
env_list =
    py311
    py312
    py313
    py314

[testenv]
extras = dev
commands = 
    py314: pylint transit/ trip_planner/
    py314: bandit -r transit/
    py314: bandit -r trip_planner/
    pytest --cov=transit/ --cov=trip_planner/ --cov-report=xml --cov-fail-under=100 tests/

[pytest]
filterwarnings = error
