name: Tag build

on:
  push:
    branches:
    - main

jobs:
  tag_build:
    uses: tnoff/github-workflows/.github/workflows/tag.yml@ace23270fbc86eea0152c1cd2b186a03d9839072
    with:
      version_file: ./VERSION
