name: Tag build

on:
  push:
    branches:
    - main

jobs:
  tag_build:
    uses: tnoff/github-workflows/.github/workflows/tag.yml@5a3473dcbf9095c0e2137fa209bf1d10bc9f791f
    with:
      version_file: ./VERSION
