name: Tag build

on:
  push:
    branches:
    - main

jobs:
  tag_build:
    uses: tnoff/github-workflows/.github/workflows/tag.yml@67a771844f0c59a3e310920197cc173be4d5805b
    with:
      version_file: ./VERSION
