name: Coverage Upload

on:
  push:
    branches: [main]

jobs:
  store-coverage:
    uses: tnoff/github-workflows/.github/workflows/coverage-store.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      coverage_source: transit trip_planner
      install_command: pip install -r requirements.txt -r tests/requirements.txt
      python_version: 3.14
