name: Coverage Upload

on:
  push:
    branches: [main]

jobs:
  store-coverage:
    uses: tnoff/github-workflows/.github/workflows/coverage-store.yml@5c01c5cfcd5237914aee049f8b681b1a0b6215cc
    with:
      coverage_source: transit trip_planner
      install_command: pip install -r requirements.txt -r tests/requirements.txt
      python_version: 3.14
