name: Dependabot Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # test requirements: any update type, filtered by path
  auto-approve-test-reqs:
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@5a3473dcbf9095c0e2137fa209bf1d10bc9f791f
    with:
      file_pattern: 'tests/**'
      allowed_update_types: 'major,minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}
