name: Dependabot Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # test requirements: any update type, filtered by path
  auto-approve-test-reqs:
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@1dcefc7c5dfeb21105e3256bf21fc97b8552252e
    with:
      file_pattern: 'tests/**'
      allowed_update_types: 'major,minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}
