name: Dependabot Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # test requirements: any update type, filtered by path
  auto-approve-test-reqs:
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@ace23270fbc86eea0152c1cd2b186a03d9839072
    with:
      file_pattern: 'tests/**'
      allowed_update_types: 'major,minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}
