name: Tag build

on:
  push:
    branches:
    - master

jobs:
  tag_build:
    name: Tag Build if doesn't exist already
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Get version
        id: version
        run: echo "version=v$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Check If Tag already exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: ${{ steps.version.outputs.version }}
      - run: echo "Tag exists!"
        if: steps.check-tag.outputs.exists == 'true'
      - name: Add tag
        id: tag-version
        if: steps.check-tag.outputs.exists != 'true'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
          tag_prefix: ''